/**
 * Seed des joueurs pour les 24 équipes de la CAN 2025
 * Environ 25 joueurs par équipe (600 joueurs au total)
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const players = [
  // ========== GROUPE A - MAROC ==========
  // Gardiens
  { teamCode: "MAR", name: "Yassine Bounou", position: "GOALKEEPER", number: 1 },
  { teamCode: "MAR", name: "Munir Mohamedi", position: "GOALKEEPER", number: 22 },
  { teamCode: "MAR", name: "Ahmed Reda Tagnaouti", position: "GOALKEEPER", number: 12 },
  // Défenseurs
  { teamCode: "MAR", name: "Achraf Hakimi", position: "DEFENDER", number: 2 },
  { teamCode: "MAR", name: "Noussair Mazraoui", position: "DEFENDER", number: 3 },
  { teamCode: "MAR", name: "Romain Saïss", position: "DEFENDER", number: 6 },
  { teamCode: "MAR", name: "Nayef Aguerd", position: "DEFENDER", number: 5 },
  { teamCode: "MAR", name: "Achraf Dari", position: "DEFENDER", number: 4 },
  { teamCode: "MAR", name: "Yahia Attiat-Allah", position: "DEFENDER", number: 25 },
  // Milieux
  { teamCode: "MAR", name: "Sofyan Amrabat", position: "MIDFIELDER", number: 8 },
  { teamCode: "MAR", name: "Azzedine Ounahi", position: "MIDFIELDER", number: 7 },
  { teamCode: "MAR", name: "Bilal El Khannouss", position: "MIDFIELDER", number: 11 },
  { teamCode: "MAR", name: "Amine Harit", position: "MIDFIELDER", number: 14 },
  { teamCode: "MAR", name: "Ismael Saibari", position: "MIDFIELDER", number: 17 },
  { teamCode: "MAR", name: "Amir Richardson", position: "MIDFIELDER", number: 15 },
  // Attaquants
  { teamCode: "MAR", name: "Youssef En-Nesyri", position: "FORWARD", number: 19 },
  { teamCode: "MAR", name: "Hakim Ziyech", position: "FORWARD", number: 10 },
  { teamCode: "MAR", name: "Sofiane Boufal", position: "FORWARD", number: 20 },
  { teamCode: "MAR", name: "Abde Ezzalzouli", position: "FORWARD", number: 16 },
  { teamCode: "MAR", name: "Ilias Akhomach", position: "FORWARD", number: 18 },
  { teamCode: "MAR", name: "Ayoub El Kaabi", position: "FORWARD", number: 9 },
  { teamCode: "MAR", name: "Zakaria Aboukhlal", position: "FORWARD", number: 21 },

  // ========== GROUPE A - MALI ==========
  { teamCode: "MLI", name: "Djigui Diarra", position: "GOALKEEPER", number: 16 },
  { teamCode: "MLI", name: "Morikano Koné", position: "GOALKEEPER", number: 1 },
  { teamCode: "MLI", name: "Mamadou Samassa", position: "GOALKEEPER", number: 22 },
  { teamCode: "MLI", name: "Falaye Sacko", position: "DEFENDER", number: 2 },
  { teamCode: "MLI", name: "Boubacar Kouyaté", position: "DEFENDER", number: 5 },
  { teamCode: "MLI", name: "Sikou Niakaté", position: "DEFENDER", number: 4 },
  { teamCode: "MLI", name: "Massadio Haïdara", position: "DEFENDER", number: 3 },
  { teamCode: "MLI", name: "Hamari Traoré", position: "DEFENDER", number: 12 },
  { teamCode: "MLI", name: "Amadou Haidara", position: "MIDFIELDER", number: 6 },
  { teamCode: "MLI", name: "Yves Bissouma", position: "MIDFIELDER", number: 8 },
  { teamCode: "MLI", name: "Lassana Coulibaly", position: "MIDFIELDER", number: 13 },
  { teamCode: "MLI", name: "Kamory Doumbia", position: "MIDFIELDER", number: 18 },
  { teamCode: "MLI", name: "Aliou Dieng", position: "MIDFIELDER", number: 14 },
  { teamCode: "MLI", name: "Adama Traoré", position: "FORWARD", number: 10 },
  { teamCode: "MLI", name: "El Bilal Touré", position: "FORWARD", number: 9 },
  { teamCode: "MLI", name: "Moussa Djenepo", position: "FORWARD", number: 11 },
  { teamCode: "MLI", name: "Sékou Koïta", position: "FORWARD", number: 7 },
  { teamCode: "MLI", name: "Yoane Wissa", position: "FORWARD", number: 20 },
  { teamCode: "MLI", name: "Kalifa Coulibaly", position: "FORWARD", number: 19 },
  { teamCode: "MLI", name: "Ibrahima Koné", position: "FORWARD", number: 21 },
  { teamCode: "MLI", name: "Adama Noss Traoré", position: "MIDFIELDER", number: 15 },
  { teamCode: "MLI", name: "Diadie Samassekou", position: "MIDFIELDER", number: 17 },

  // ========== GROUPE A - ZAMBIE ==========
  { teamCode: "ZAM", name: "Lawrence Mulenga", position: "GOALKEEPER", number: 16 },
  { teamCode: "ZAM", name: "Toaster Nsabata", position: "GOALKEEPER", number: 1 },
  { teamCode: "ZAM", name: "Sebastian Mwange", position: "GOALKEEPER", number: 18 },
  { teamCode: "ZAM", name: "Tandi Mwape", position: "DEFENDER", number: 13 },
  { teamCode: "ZAM", name: "Stoppila Sunzu", position: "DEFENDER", number: 4 },
  { teamCode: "ZAM", name: "Frankie Musonda", position: "DEFENDER", number: 5 },
  { teamCode: "ZAM", name: "Roderick Kabwe", position: "DEFENDER", number: 2 },
  { teamCode: "ZAM", name: "Benedict Chepeshi", position: "DEFENDER", number: 3 },
  { teamCode: "ZAM", name: "Kings Kangwa", position: "MIDFIELDER", number: 11 },
  { teamCode: "ZAM", name: "Emmanuel Banda", position: "MIDFIELDER", number: 17 },
  { teamCode: "ZAM", name: "Kelvin Kapumbu", position: "MIDFIELDER", number: 8 },
  { teamCode: "ZAM", name: "Edward Chilufya", position: "MIDFIELDER", number: 7 },
  { teamCode: "ZAM", name: "Lameck Banda", position: "MIDFIELDER", number: 10 },
  { teamCode: "ZAM", name: "Fashion Sakala", position: "FORWARD", number: 9 },
  { teamCode: "ZAM", name: "Patson Daka", position: "FORWARD", number: 20 },
  { teamCode: "ZAM", name: "Clatous Chama", position: "FORWARD", number: 14 },
  { teamCode: "ZAM", name: "Kennedy Musonda", position: "FORWARD", number: 19 },
  { teamCode: "ZAM", name: "Rally Bwalya", position: "MIDFIELDER", number: 15 },
  { teamCode: "ZAM", name: "Golden Mafwenta", position: "MIDFIELDER", number: 6 },
  { teamCode: "ZAM", name: "Lubambo Musonda", position: "DEFENDER", number: 12 },
  { teamCode: "ZAM", name: "Dominic Chanda", position: "DEFENDER", number: 22 },

  // ========== GROUPE A - COMORES ==========
  { teamCode: "COM", name: "Ali Ahamada", position: "GOALKEEPER", number: 16 },
  { teamCode: "COM", name: "Salim Ben Boina", position: "GOALKEEPER", number: 23 },
  { teamCode: "COM", name: "Moyadh Ousseini", position: "GOALKEEPER", number: 1 },
  { teamCode: "COM", name: "Chaker Alhadhur", position: "DEFENDER", number: 5 },
  { teamCode: "COM", name: "Kassim Abdallah", position: "DEFENDER", number: 13 },
  { teamCode: "COM", name: "Younn Zahary", position: "DEFENDER", number: 3 },
  { teamCode: "COM", name: "Akim Abdallah", position: "DEFENDER", number: 2 },
  { teamCode: "COM", name: "Mohamed Youssouf", position: "DEFENDER", number: 15 },
  { teamCode: "COM", name: "Yacine Bourhane", position: "MIDFIELDER", number: 6 },
  { teamCode: "COM", name: "Nadjim Abdou", position: "MIDFIELDER", number: 14 },
  { teamCode: "COM", name: "Rafidine Abdullah", position: "MIDFIELDER", number: 12 },
  { teamCode: "COM", name: "Youssouf M'Changama", position: "MIDFIELDER", number: 10 },
  { teamCode: "COM", name: "Ibroihim Youssouf", position: "MIDFIELDER", number: 8 },
  { teamCode: "COM", name: "Faïz Selemani", position: "FORWARD", number: 7 },
  { teamCode: "COM", name: "El Fardou Ben Nabouhane", position: "FORWARD", number: 9 },
  { teamCode: "COM", name: "Rafiki Said", position: "FORWARD", number: 11 },
  { teamCode: "COM", name: "Myziane Maolida", position: "FORWARD", number: 17 },
  { teamCode: "COM", name: "Bendjaloud Youssouf", position: "MIDFIELDER", number: 4 },
  { teamCode: "COM", name: "Faïz Mattoir", position: "DEFENDER", number: 19 },
  { teamCode: "COM", name: "Mohamed M'Changama", position: "MIDFIELDER", number: 18 },
  { teamCode: "COM", name: "Ahmed Abdallah", position: "DEFENDER", number: 21 },

  // ========== GROUPE B - ÉGYPTE ==========
  { teamCode: "EGY", name: "Mohamed El Shenawy", position: "GOALKEEPER", number: 16 },
  { teamCode: "EGY", name: "Mohamed Abou Gabal", position: "GOALKEEPER", number: 1 },
  { teamCode: "EGY", name: "Ahmed El Shennawy", position: "GOALKEEPER", number: 22 },
  { teamCode: "EGY", name: "Ahmed Hegazy", position: "DEFENDER", number: 6 },
  { teamCode: "EGY", name: "Mohamed Abdel-Monem", position: "DEFENDER", number: 2 },
  { teamCode: "EGY", name: "Omar Kamal", position: "DEFENDER", number: 3 },
  { teamCode: "EGY", name: "Mohamed Hamdy", position: "DEFENDER", number: 12 },
  { teamCode: "EGY", name: "Akram Tawfik", position: "DEFENDER", number: 13 },
  { teamCode: "EGY", name: "Mohamed Elneny", position: "MIDFIELDER", number: 4 },
  { teamCode: "EGY", name: "Emam Ashour", position: "MIDFIELDER", number: 8 },
  { teamCode: "EGY", name: "Zizo", position: "MIDFIELDER", number: 11 },
  { teamCode: "EGY", name: "Marwan Attia", position: "MIDFIELDER", number: 17 },
  { teamCode: "EGY", name: "Mohamed Salah", position: "FORWARD", number: 10 },
  { teamCode: "EGY", name: "Omar Marmoush", position: "FORWARD", number: 7 },
  { teamCode: "EGY", name: "Mostafa Mohamed", position: "FORWARD", number: 9 },
  { teamCode: "EGY", name: "Trézéguet", position: "FORWARD", number: 19 },
  { teamCode: "EGY", name: "Ibrahim Adel", position: "FORWARD", number: 20 },
  { teamCode: "EGY", name: "Hamdi Fathi", position: "MIDFIELDER", number: 5 },
  { teamCode: "EGY", name: "Ahmed Sayed Zizo", position: "MIDFIELDER", number: 14 },
  { teamCode: "EGY", name: "Mahmoud Hassan Trezeguet", position: "FORWARD", number: 18 },
  { teamCode: "EGY", name: "Afsha", position: "MIDFIELDER", number: 15 },
  { teamCode: "EGY", name: "Kahraba", position: "FORWARD", number: 21 },

  // ========== GROUPE B - AFRIQUE DU SUD ==========
  { teamCode: "RSA", name: "Ronwen Williams", position: "GOALKEEPER", number: 1 },
  { teamCode: "RSA", name: "Veli Mothwa", position: "GOALKEEPER", number: 16 },
  { teamCode: "RSA", name: "Ricardo Goss", position: "GOALKEEPER", number: 22 },
  { teamCode: "RSA", name: "Khuliso Mudau", position: "DEFENDER", number: 20 },
  { teamCode: "RSA", name: "Nkosinathi Sibisi", position: "DEFENDER", number: 3 },
  { teamCode: "RSA", name: "Mothobi Mvala", position: "DEFENDER", number: 14 },
  { teamCode: "RSA", name: "Siyanda Xulu", position: "DEFENDER", number: 5 },
  { teamCode: "RSA", name: "Aubrey Modiba", position: "DEFENDER", number: 6 },
  { teamCode: "RSA", name: "Teboho Mokoena", position: "MIDFIELDER", number: 4 },
  { teamCode: "RSA", name: "Luke Le Roux", position: "MIDFIELDER", number: 13 },
  { teamCode: "RSA", name: "Thapelo Morena", position: "MIDFIELDER", number: 12 },
  { teamCode: "RSA", name: "Themba Zwane", position: "MIDFIELDER", number: 11 },
  { teamCode: "RSA", name: "Evidence Makgopa", position: "FORWARD", number: 9 },
  { teamCode: "RSA", name: "Percy Tau", position: "FORWARD", number: 10 },
  { teamCode: "RSA", name: "Mihlali Mayambela", position: "FORWARD", number: 7 },
  { teamCode: "RSA", name: "Zakhele Lepasa", position: "FORWARD", number: 19 },
  { teamCode: "RSA", name: "Oswin Appollis", position: "FORWARD", number: 17 },
  { teamCode: "RSA", name: "Terrence Mashego", position: "DEFENDER", number: 2 },
  { teamCode: "RSA", name: "Thabang Monare", position: "MIDFIELDER", number: 8 },
  { teamCode: "RSA", name: "Grant Margeman", position: "MIDFIELDER", number: 15 },
  { teamCode: "RSA", name: "Relebohile Mofokeng", position: "FORWARD", number: 18 },

  // ========== GROUPE B - ANGOLA ==========
  { teamCode: "ANG", name: "Neblú", position: "GOALKEEPER", number: 22 },
  { teamCode: "ANG", name: "Hugo Marques", position: "GOALKEEPER", number: 1 },
  { teamCode: "ANG", name: "Landu", position: "GOALKEEPER", number: 12 },
  { teamCode: "ANG", name: "Kialonda Gaspar", position: "DEFENDER", number: 3 },
  { teamCode: "ANG", name: "Jonathan Buatu", position: "DEFENDER", number: 4 },
  { teamCode: "ANG", name: "Núrio Fortuna", position: "DEFENDER", number: 5 },
  { teamCode: "ANG", name: "Eddie", position: "DEFENDER", number: 13 },
  { teamCode: "ANG", name: "Clinton Mata", position: "DEFENDER", number: 2 },
  { teamCode: "ANG", name: "Show", position: "MIDFIELDER", number: 6 },
  { teamCode: "ANG", name: "Fredy", position: "MIDFIELDER", number: 8 },
  { teamCode: "ANG", name: "Estrela", position: "MIDFIELDER", number: 10 },
  { teamCode: "ANG", name: "Maestro", position: "MIDFIELDER", number: 14 },
  { teamCode: "ANG", name: "Zini", position: "MIDFIELDER", number: 15 },
  { teamCode: "ANG", name: "Gelson Dala", position: "FORWARD", number: 7 },
  { teamCode: "ANG", name: "Mabululu", position: "FORWARD", number: 9 },
  { teamCode: "ANG", name: "Zito Luvumbo", position: "FORWARD", number: 11 },
  { teamCode: "ANG", name: "Gilberto", position: "FORWARD", number: 17 },
  { teamCode: "ANG", name: "Jérémie Bela", position: "FORWARD", number: 20 },
  { teamCode: "ANG", name: "Paizo", position: "MIDFIELDER", number: 16 },
  { teamCode: "ANG", name: "Herenilson", position: "DEFENDER", number: 19 },
  { teamCode: "ANG", name: "Keliano", position: "MIDFIELDER", number: 18 },

  // ========== GROUPE B - ZIMBABWE ==========
  { teamCode: "ZIM", name: "Bernard Donovan", position: "GOALKEEPER", number: 1 },
  { teamCode: "ZIM", name: "Geoffrey Chitsumba", position: "GOALKEEPER", number: 16 },
  { teamCode: "ZIM", name: "Washington Arubi", position: "GOALKEEPER", number: 23 },
  { teamCode: "ZIM", name: "Divine Lunga", position: "DEFENDER", number: 3 },
  { teamCode: "ZIM", name: "Teenage Hadebe", position: "DEFENDER", number: 15 },
  { teamCode: "ZIM", name: "Munashe Garananga", position: "DEFENDER", number: 4 },
  { teamCode: "ZIM", name: "Godknows Murwira", position: "DEFENDER", number: 2 },
  { teamCode: "ZIM", name: "Gerald Takwara", position: "DEFENDER", number: 13 },
  { teamCode: "ZIM", name: "Marshall Munetsi", position: "MIDFIELDER", number: 7 },
  { teamCode: "ZIM", name: "Tino Kadewere", position: "MIDFIELDER", number: 11 },
  { teamCode: "ZIM", name: "Marvelous Nakamba", position: "MIDFIELDER", number: 6 },
  { teamCode: "ZIM", name: "Richard Hachiro", position: "MIDFIELDER", number: 8 },
  { teamCode: "ZIM", name: "Admiral Muskwe", position: "FORWARD", number: 9 },
  { teamCode: "ZIM", name: "Khama Billiat", position: "FORWARD", number: 10 },
  { teamCode: "ZIM", name: "Knowledge Musona", position: "FORWARD", number: 14 },
  { teamCode: "ZIM", name: "Douglas Mapfumo", position: "FORWARD", number: 17 },
  { teamCode: "ZIM", name: "Prince Dube", position: "FORWARD", number: 19 },
  { teamCode: "ZIM", name: "Ishmael Wadi", position: "MIDFIELDER", number: 12 },
  { teamCode: "ZIM", name: "Jordan Zemura", position: "DEFENDER", number: 20 },
  { teamCode: "ZIM", name: "Never Tigere", position: "MIDFIELDER", number: 18 },

  // ========== GROUPE D - SÉNÉGAL ==========
  { teamCode: "SEN", name: "Édouard Mendy", position: "GOALKEEPER", number: 16 },
  { teamCode: "SEN", name: "Seny Dieng", position: "GOALKEEPER", number: 1 },
  { teamCode: "SEN", name: "Mory Diaw", position: "GOALKEEPER", number: 23 },
  { teamCode: "SEN", name: "Kalidou Koulibaly", position: "DEFENDER", number: 3 },
  { teamCode: "SEN", name: "Abdou Diallo", position: "DEFENDER", number: 22 },
  { teamCode: "SEN", name: "Youssouf Sabaly", position: "DEFENDER", number: 18 },
  { teamCode: "SEN", name: "Pape Abou Cissé", position: "DEFENDER", number: 4 },
  { teamCode: "SEN", name: "Ismail Jakobs", position: "DEFENDER", number: 14 },
  { teamCode: "SEN", name: "Idrissa Gana Gueye", position: "MIDFIELDER", number: 5 },
  { teamCode: "SEN", name: "Pape Matar Sarr", position: "MIDFIELDER", number: 26 },
  { teamCode: "SEN", name: "Pape Gueye", position: "MIDFIELDER", number: 6 },
  { teamCode: "SEN", name: "Krepin Diatta", position: "MIDFIELDER", number: 15 },
  { teamCode: "SEN", name: "Sadio Mané", position: "FORWARD", number: 10 },
  { teamCode: "SEN", name: "Ismaïla Sarr", position: "FORWARD", number: 9 },
  { teamCode: "SEN", name: "Nicolas Jackson", position: "FORWARD", number: 20 },
  { teamCode: "SEN", name: "Iliman Ndiaye", position: "FORWARD", number: 13 },
  { teamCode: "SEN", name: "Habib Diallo", position: "FORWARD", number: 19 },
  { teamCode: "SEN", name: "Lamine Camara", position: "MIDFIELDER", number: 17 },
  { teamCode: "SEN", name: "Formose Mendy", position: "DEFENDER", number: 2 },
  { teamCode: "SEN", name: "Boulaye Dia", position: "FORWARD", number: 11 },
  { teamCode: "SEN", name: "Pathé Ciss", position: "MIDFIELDER", number: 8 },

  // ========== GROUPE F - CAMEROUN ==========
  { teamCode: "CMR", name: "André Onana", position: "GOALKEEPER", number: 1 },
  { teamCode: "CMR", name: "Devis Epassy", position: "GOALKEEPER", number: 16 },
  { teamCode: "CMR", name: "Simon Ngapandouetnbu", position: "GOALKEEPER", number: 23 },
  { teamCode: "CMR", name: "Jean-Charles Castelletto", position: "DEFENDER", number: 21 },
  { teamCode: "CMR", name: "Nouhou Tolo", position: "DEFENDER", number: 3 },
  { teamCode: "CMR", name: "Enzo Ebosse", position: "DEFENDER", number: 25 },
  { teamCode: "CMR", name: "Christopher Wooh", position: "DEFENDER", number: 4 },
  { teamCode: "CMR", name: "Harold Moukoudi", position: "DEFENDER", number: 5 },
  { teamCode: "CMR", name: "André-Frank Zambo Anguissa", position: "MIDFIELDER", number: 8 },
  { teamCode: "CMR", name: "Samuel Oum Gouet", position: "MIDFIELDER", number: 18 },
  { teamCode: "CMR", name: "Olivier Kemen", position: "MIDFIELDER", number: 20 },
  { teamCode: "CMR", name: "Martin Hongla", position: "MIDFIELDER", number: 15 },
  { teamCode: "CMR", name: "Vincent Aboubakar", position: "FORWARD", number: 10 },
  { teamCode: "CMR", name: "Bryan Mbeumo", position: "FORWARD", number: 14 },
  { teamCode: "CMR", name: "Karl Toko Ekambi", position: "FORWARD", number: 12 },
  { teamCode: "CMR", name: "Georges-Kévin Nkoudou", position: "FORWARD", number: 7 },
  { teamCode: "CMR", name: "Jean-Pierre Nsame", position: "FORWARD", number: 9 },
  { teamCode: "CMR", name: "Moumi Ngamaleu", position: "FORWARD", number: 11 },
  { teamCode: "CMR", name: "Frank Magri", position: "FORWARD", number: 13 },
  { teamCode: "CMR", name: "Olivier Ntcham", position: "MIDFIELDER", number: 17 },
  { teamCode: "CMR", name: "Collins Fai", position: "DEFENDER", number: 19 },

  // ========== GROUPE D - RD CONGO ==========
  { teamCode: "COD", name: "Lionel Mpasi", position: "GOALKEEPER", number: 1 },
  { teamCode: "COD", name: "Brudel Luyeye", position: "GOALKEEPER", number: 16 },
  { teamCode: "COD", name: "Ley Matampi", position: "GOALKEEPER", number: 22 },
  { teamCode: "COD", name: "Chancel Mbemba", position: "DEFENDER", number: 2 },
  { teamCode: "COD", name: "Arthur Masuaku", position: "DEFENDER", number: 26 },
  { teamCode: "COD", name: "Dylan Batubinsika", position: "DEFENDER", number: 22 },
  { teamCode: "COD", name: "Aaron Tshibola", position: "DEFENDER", number: 5 },
  { teamCode: "COD", name: "Henock Inonga", position: "DEFENDER", number: 3 },
  { teamCode: "COD", name: "Samuel Moutoussamy", position: "MIDFIELDER", number: 8 },
  { teamCode: "COD", name: "Gédéon Kalulu", position: "MIDFIELDER", number: 18 },
  { teamCode: "COD", name: "Charles Pickel", position: "MIDFIELDER", number: 24 },
  { teamCode: "COD", name: "Théo Bongonda", position: "MIDFIELDER", number: 11 },
  { teamCode: "COD", name: "Yoane Wissa", position: "FORWARD", number: 14 },
  { teamCode: "COD", name: "Cédric Bakambu", position: "FORWARD", number: 17 },
  { teamCode: "COD", name: "Silas Katompa Mvumpa", position: "FORWARD", number: 25 },
  { teamCode: "COD", name: "Gaël Kakuta", position: "MIDFIELDER", number: 10 },
  { teamCode: "COD", name: "Meschack Elia", position: "FORWARD", number: 7 },
  { teamCode: "COD", name: "Fiston Mayele", position: "FORWARD", number: 9 },
  { teamCode: "COD", name: "Simon Banza", position: "FORWARD", number: 20 },
  { teamCode: "COD", name: "Omenuke Mfulu", position: "MIDFIELDER", number: 6 },
  { teamCode: "COD", name: "Rocky Bushiri", position: "DEFENDER", number: 4 },

  // ========== GROUPE C - TANZANIE ==========
  { teamCode: "TAN", name: "Aishi Manula", position: "GOALKEEPER", number: 1 },
  { teamCode: "TAN", name: "Metacha Mnata", position: "GOALKEEPER", number: 16 },
  { teamCode: "TAN", name: "Ally Salim", position: "GOALKEEPER", number: 18 },
  { teamCode: "TAN", name: "Novatus Miroshi", position: "DEFENDER", number: 2 },
  { teamCode: "TAN", name: "Morice Abraham", position: "DEFENDER", number: 13 },
  { teamCode: "TAN", name: "Ibrahim Hamad", position: "DEFENDER", number: 3 },
  { teamCode: "TAN", name: "Bakari Mwamnyeto", position: "DEFENDER", number: 4 },
  { teamCode: "TAN", name: "Haji Mnoga", position: "DEFENDER", number: 5 },
  { teamCode: "TAN", name: "Mudathir Yahya", position: "MIDFIELDER", number: 6 },
  { teamCode: "TAN", name: "Feisal Salum", position: "MIDFIELDER", number: 8 },
  { teamCode: "TAN", name: "Novatus Dismas", position: "MIDFIELDER", number: 10 },
  { teamCode: "TAN", name: "Simon Msuva", position: "MIDFIELDER", number: 11 },
  { teamCode: "TAN", name: "Mbwana Samatta", position: "FORWARD", number: 9 },
  { teamCode: "TAN", name: "Thomas Ulimwengu", position: "FORWARD", number: 7 },
  { teamCode: "TAN", name: "John Bocco", position: "FORWARD", number: 14 },
  { teamCode: "TAN", name: "Himid Mao", position: "FORWARD", number: 17 },
  { teamCode: "TAN", name: "Farid Mussa", position: "MIDFIELDER", number: 12 },
  { teamCode: "TAN", name: "Kelvin Yondani", position: "DEFENDER", number: 15 },
  { teamCode: "TAN", name: "Lusajo Mwaikenda", position: "MIDFIELDER", number: 19 },
  { teamCode: "TAN", name: "Said Ndemla", position: "MIDFIELDER", number: 20 },

  // ========== GROUPE E - ALGÉRIE ==========
  { teamCode: "ALG", name: "Anthony Mandrea", position: "GOALKEEPER", number: 23 },
  { teamCode: "ALG", name: "Alexis Guendouz", position: "GOALKEEPER", number: 1 },
  { teamCode: "ALG", name: "Mustapha Zeghba", position: "GOALKEEPER", number: 16 },
  { teamCode: "ALG", name: "Ramy Bensebaini", position: "DEFENDER", number: 3 },
  { teamCode: "ALG", name: "Mohamed Amine Tougai", position: "DEFENDER", number: 2 },
  { teamCode: "ALG", name: "Aïssa Mandi", position: "DEFENDER", number: 12 },
  { teamCode: "ALG", name: "Youcef Atal", position: "DEFENDER", number: 20 },
  { teamCode: "ALG", name: "Jaouen Hadjam", position: "DEFENDER", number: 25 },
  { teamCode: "ALG", name: "Houssem Aouar", position: "MIDFIELDER", number: 18 },
  { teamCode: "ALG", name: "Ramiz Zerrouki", position: "MIDFIELDER", number: 6 },
  { teamCode: "ALG", name: "Nabil Bentaleb", position: "MIDFIELDER", number: 8 },
  { teamCode: "ALG", name: "Amine Gouiri", position: "FORWARD", number: 14 },
  { teamCode: "ALG", name: "Riyad Mahrez", position: "FORWARD", number: 7 },
  { teamCode: "ALG", name: "Islam Slimani", position: "FORWARD", number: 13 },
  { teamCode: "ALG", name: "Baghdad Bounedjah", position: "FORWARD", number: 9 },
  { teamCode: "ALG", name: "Youcef Belaïli", position: "FORWARD", number: 10 },
  { teamCode: "ALG", name: "Saïd Benrahma", position: "FORWARD", number: 17 },
  { teamCode: "ALG", name: "Mohamed Amoura", position: "FORWARD", number: 19 },
  { teamCode: "ALG", name: "Ismael Bennacer", position: "MIDFIELDER", number: 15 },
  { teamCode: "ALG", name: "Reda Belahyane", position: "MIDFIELDER", number: 5 },
  { teamCode: "ALG", name: "Farès Chaïbi", position: "MIDFIELDER", number: 11 },

  // ========== GROUPE C - NIGERIA ==========
  { teamCode: "NGA", name: "Stanley Nwabali", position: "GOALKEEPER", number: 23 },
  { teamCode: "NGA", name: "Francis Uzoho", position: "GOALKEEPER", number: 1 },
  { teamCode: "NGA", name: "Maduka Okoye", position: "GOALKEEPER", number: 16 },
  { teamCode: "NGA", name: "William Troost-Ekong", position: "DEFENDER", number: 5 },
  { teamCode: "NGA", name: "Kenneth Omeruo", position: "DEFENDER", number: 22 },
  { teamCode: "NGA", name: "Calvin Bassey", position: "DEFENDER", number: 3 },
  { teamCode: "NGA", name: "Ola Aina", position: "DEFENDER", number: 2 },
  { teamCode: "NGA", name: "Zaidu Sanusi", position: "DEFENDER", number: 12 },
  { teamCode: "NGA", name: "Wilfred Ndidi", position: "MIDFIELDER", number: 4 },
  { teamCode: "NGA", name: "Frank Onyeka", position: "MIDFIELDER", number: 8 },
  { teamCode: "NGA", name: "Alex Iwobi", position: "MIDFIELDER", number: 17 },
  { teamCode: "NGA", name: "Joe Aribo", position: "MIDFIELDER", number: 10 },
  { teamCode: "NGA", name: "Victor Osimhen", position: "FORWARD", number: 9 },
  { teamCode: "NGA", name: "Samuel Chukwueze", position: "FORWARD", number: 11 },
  { teamCode: "NGA", name: "Ademola Lookman", position: "FORWARD", number: 14 },
  { teamCode: "NGA", name: "Moses Simon", position: "FORWARD", number: 15 },
  { teamCode: "NGA", name: "Kelechi Iheanacho", position: "FORWARD", number: 7 },
  { teamCode: "NGA", name: "Victor Boniface", position: "FORWARD", number: 18 },
  { teamCode: "NGA", name: "Raphael Onyedika", position: "MIDFIELDER", number: 6 },
  { teamCode: "NGA", name: "Bright Osayi-Samuel", position: "DEFENDER", number: 20 },
  { teamCode: "NGA", name: "Semi Ajayi", position: "DEFENDER", number: 13 },

  // ========== GROUPE D - TUNISIE ==========
  { teamCode: "TUN", name: "Aymen Dahmen", position: "GOALKEEPER", number: 16 },
  { teamCode: "TUN", name: "Bechir Ben Saïd", position: "GOALKEEPER", number: 22 },
  { teamCode: "TUN", name: "Mouez Hassen", position: "GOALKEEPER", number: 1 },
  { teamCode: "TUN", name: "Ali Maâloul", position: "DEFENDER", number: 12 },
  { teamCode: "TUN", name: "Dylan Bronn", position: "DEFENDER", number: 3 },
  { teamCode: "TUN", name: "Montassar Talbi", position: "DEFENDER", number: 4 },
  { teamCode: "TUN", name: "Nader Ghandri", position: "DEFENDER", number: 2 },
  { teamCode: "TUN", name: "Wajdi Kechrida", position: "DEFENDER", number: 21 },
  { teamCode: "TUN", name: "Aïssa Laïdouni", position: "MIDFIELDER", number: 14 },
  { teamCode: "TUN", name: "Ellyes Skhiri", position: "MIDFIELDER", number: 17 },
  { teamCode: "TUN", name: "Mohamed Ali Ben Romdhane", position: "MIDFIELDER", number: 24 },
  { teamCode: "TUN", name: "Ferjani Sassi", position: "MIDFIELDER", number: 13 },
  { teamCode: "TUN", name: "Youssef Msakni", position: "FORWARD", number: 7 },
  { teamCode: "TUN", name: "Wahbi Khazri", position: "FORWARD", number: 10 },
  { teamCode: "TUN", name: "Seifeddine Jaziri", position: "FORWARD", number: 11 },
  { teamCode: "TUN", name: "Anis Ben Slimane", position: "MIDFIELDER", number: 23 },
  { teamCode: "TUN", name: "Issam Jebali", position: "FORWARD", number: 19 },
  { teamCode: "TUN", name: "Taha Khenissi", position: "FORWARD", number: 9 },
  { teamCode: "TUN", name: "Hannibal Mejbri", position: "MIDFIELDER", number: 15 },
  { teamCode: "TUN", name: "Haythem Jouini", position: "FORWARD", number: 20 },
  { teamCode: "TUN", name: "Yassine Meriah", position: "DEFENDER", number: 5 },

  // ========== GROUPE D - SOUDAN ==========
  { teamCode: "SUD", name: "Ali Abu Eshrein", position: "GOALKEEPER", number: 1 },
  { teamCode: "SUD", name: "Mohamed Mustafa", position: "GOALKEEPER", number: 16 },
  { teamCode: "SUD", name: "Mohamed El Mustafa", position: "GOALKEEPER", number: 22 },
  { teamCode: "SUD", name: "Mustafa Elfadni", position: "DEFENDER", number: 2 },
  { teamCode: "SUD", name: "Mohamed Abdelrahman", position: "DEFENDER", number: 6 },
  { teamCode: "SUD", name: "Mazin Mohamedein", position: "DEFENDER", number: 3 },
  { teamCode: "SUD", name: "Salah Nemer", position: "DEFENDER", number: 5 },
  { teamCode: "SUD", name: "Ahmed Mahmoud", position: "DEFENDER", number: 12 },
  { teamCode: "SUD", name: "Ramadan Agab", position: "MIDFIELDER", number: 8 },
  { teamCode: "SUD", name: "Mohamed Abdelrahman Yousif", position: "MIDFIELDER", number: 7 },
  { teamCode: "SUD", name: "Walieldin Khedr", position: "MIDFIELDER", number: 17 },
  { teamCode: "SUD", name: "Bakhit Khamis", position: "MIDFIELDER", number: 18 },
  { teamCode: "SUD", name: "Yasir Mozamil", position: "FORWARD", number: 11 },
  { teamCode: "SUD", name: "Mohamed Abdel Rahman", position: "FORWARD", number: 10 },
  { teamCode: "SUD", name: "Abo Eisa", position: "FORWARD", number: 9 },
  { teamCode: "SUD", name: "Saif Terry", position: "FORWARD", number: 14 },
  { teamCode: "SUD", name: "Ahmed Hamid", position: "MIDFIELDER", number: 13 },
  { teamCode: "SUD", name: "Abdelrazig Omer", position: "MIDFIELDER", number: 15 },
  { teamCode: "SUD", name: "Mustafa Karshoum", position: "DEFENDER", number: 4 },
  { teamCode: "SUD", name: "Saifeldin Malik", position: "MIDFIELDER", number: 19 },

  // ========== GROUPE E - CÔTE D'IVOIRE ==========
  { teamCode: "CIV", name: "Yahia Fofana", position: "GOALKEEPER", number: 1 },
  { teamCode: "CIV", name: "Badra Ali Sangaré", position: "GOALKEEPER", number: 23 },
  { teamCode: "CIV", name: "Abdoul Karim Cissé", position: "GOALKEEPER", number: 16 },
  { teamCode: "CIV", name: "Serge Aurier", position: "DEFENDER", number: 17 },
  { teamCode: "CIV", name: "Odilon Kossounou", position: "DEFENDER", number: 5 },
  { teamCode: "CIV", name: "Evan Ndicka", position: "DEFENDER", number: 21 },
  { teamCode: "CIV", name: "Ghislain Konan", position: "DEFENDER", number: 3 },
  { teamCode: "CIV", name: "Willy Boly", position: "DEFENDER", number: 12 },
  { teamCode: "CIV", name: "Seko Fofana", position: "MIDFIELDER", number: 8 },
  { teamCode: "CIV", name: "Ibrahim Sangaré", position: "MIDFIELDER", number: 6 },
  { teamCode: "CIV", name: "Jean Michaël Seri", position: "MIDFIELDER", number: 4 },
  { teamCode: "CIV", name: "Franck Kessié", position: "MIDFIELDER", number: 20 },
  { teamCode: "CIV", name: "Sébastien Haller", position: "FORWARD", number: 22 },
  { teamCode: "CIV", name: "Nicolas Pépé", position: "FORWARD", number: 19 },
  { teamCode: "CIV", name: "Wilfried Zaha", position: "FORWARD", number: 14 },
  { teamCode: "CIV", name: "Simon Adingra", position: "FORWARD", number: 11 },
  { teamCode: "CIV", name: "Jean-Philippe Krasso", position: "FORWARD", number: 9 },
  { teamCode: "CIV", name: "Jérémie Boga", position: "FORWARD", number: 7 },
  { teamCode: "CIV", name: "Maxwel Cornet", position: "FORWARD", number: 18 },
  { teamCode: "CIV", name: "Ousmane Diomandé", position: "DEFENDER", number: 2 },
  { teamCode: "CIV", name: "Christian Kouamé", position: "FORWARD", number: 15 },

  // ========== GROUPE E - GUINÉE ÉQUATORIALE ==========
  { teamCode: "GEQ", name: "Jesús Owono", position: "GOALKEEPER", number: 1 },
  { teamCode: "GEQ", name: "Aitor Embela", position: "GOALKEEPER", number: 23 },
  { teamCode: "GEQ", name: "Manuel Sapalo", position: "GOALKEEPER", number: 13 },
  { teamCode: "GEQ", name: "Esteban Obiang", position: "DEFENDER", number: 21 },
  { teamCode: "GEQ", name: "Saúl Coco", position: "DEFENDER", number: 15 },
  { teamCode: "GEQ", name: "Basilio Ndong", position: "DEFENDER", number: 3 },
  { teamCode: "GEQ", name: "Carlos Akapo", position: "DEFENDER", number: 2 },
  { teamCode: "GEQ", name: "Marvin Anieboh", position: "DEFENDER", number: 4 },
  { teamCode: "GEQ", name: "Pablo Ganet", position: "MIDFIELDER", number: 6 },
  { teamCode: "GEQ", name: "José Machín", position: "MIDFIELDER", number: 14 },
  { teamCode: "GEQ", name: "Álex Balboa", position: "MIDFIELDER", number: 8 },
  { teamCode: "GEQ", name: "Jannick Buyla", position: "MIDFIELDER", number: 18 },
  { teamCode: "GEQ", name: "Emilio Nsue", position: "FORWARD", number: 10 },
  { teamCode: "GEQ", name: "Iban Salvador", position: "FORWARD", number: 7 },
  { teamCode: "GEQ", name: "Dorian Hanza", position: "FORWARD", number: 11 },
  { teamCode: "GEQ", name: "Santiago Eneme", position: "FORWARD", number: 9 },
  { teamCode: "GEQ", name: "José Miranda", position: "FORWARD", number: 19 },
  { teamCode: "GEQ", name: "Luis Asue", position: "FORWARD", number: 12 },
  { teamCode: "GEQ", name: "Féderico Bikoro", position: "MIDFIELDER", number: 5 },
  { teamCode: "GEQ", name: "Óscar Siafá", position: "MIDFIELDER", number: 17 },
  { teamCode: "GEQ", name: "Rubén Belima", position: "DEFENDER", number: 22 },
  { teamCode: "GEQ", name: "Josete Miranda", position: "MIDFIELDER", number: 16 },

  // ========== GROUPE E - MOZAMBIQUE ==========
  { teamCode: "MOZ", name: "Ernan Siluane", position: "GOALKEEPER", number: 1 },
  { teamCode: "MOZ", name: "Ivane Urrubal", position: "GOALKEEPER", number: 12 },
  { teamCode: "MOZ", name: "Soarito Bacar", position: "GOALKEEPER", number: 22 },
  { teamCode: "MOZ", name: "Reinildo Mandava", position: "DEFENDER", number: 5 },
  { teamCode: "MOZ", name: "Mexer", position: "DEFENDER", number: 3 },
  { teamCode: "MOZ", name: "Edmilson Dove", position: "DEFENDER", number: 4 },
  { teamCode: "MOZ", name: "Bruno Langa", position: "DEFENDER", number: 13 },
  { teamCode: "MOZ", name: "Nanani", position: "DEFENDER", number: 2 },
  { teamCode: "MOZ", name: "Guima", position: "MIDFIELDER", number: 6 },
  { teamCode: "MOZ", name: "Nené", position: "MIDFIELDER", number: 8 },
  { teamCode: "MOZ", name: "Domingues", position: "MIDFIELDER", number: 10 },
  { teamCode: "MOZ", name: "Shaquille", position: "MIDFIELDER", number: 18 },
  { teamCode: "MOZ", name: "Stanley Ratifo", position: "FORWARD", number: 7 },
  { teamCode: "MOZ", name: "Geny Catamo", position: "FORWARD", number: 11 },
  { teamCode: "MOZ", name: "Clésio Bauque", position: "FORWARD", number: 9 },
  { teamCode: "MOZ", name: "Gildo Vilanculos", position: "FORWARD", number: 14 },
  { teamCode: "MOZ", name: "Witi", position: "FORWARD", number: 17 },
  { teamCode: "MOZ", name: "Amadou", position: "MIDFIELDER", number: 15 },
  { teamCode: "MOZ", name: "Kamo Kamo", position: "DEFENDER", number: 19 },
  { teamCode: "MOZ", name: "Lau King", position: "MIDFIELDER", number: 16 },

  // ========== GROUPE E - BÉNIN ==========
  { teamCode: "BEN", name: "Marcel Dandjinou", position: "GOALKEEPER", number: 16 },
  { teamCode: "BEN", name: "Saturnin Allagbé", position: "GOALKEEPER", number: 1 },
  { teamCode: "BEN", name: "Anabard Yohan", position: "GOALKEEPER", number: 23 },
  { teamCode: "BEN", name: "Cédric Hountondji", position: "DEFENDER", number: 5 },
  { teamCode: "BEN", name: "David Kiki", position: "DEFENDER", number: 3 },
  { teamCode: "BEN", name: "Seidou Barazé", position: "DEFENDER", number: 4 },
  { teamCode: "BEN", name: "Olivier Verdon", position: "DEFENDER", number: 2 },
  { teamCode: "BEN", name: "Yohan Roche", position: "DEFENDER", number: 21 },
  { teamCode: "BEN", name: "Sessi D'Almeida", position: "MIDFIELDER", number: 6 },
  { teamCode: "BEN", name: "Mattéo Ahlinvi", position: "MIDFIELDER", number: 8 },
  { teamCode: "BEN", name: "Tosin Aiyegun", position: "MIDFIELDER", number: 14 },
  { teamCode: "BEN", name: "Dodo Dokou", position: "MIDFIELDER", number: 15 },
  { teamCode: "BEN", name: "Steve Mounié", position: "FORWARD", number: 9 },
  { teamCode: "BEN", name: "Jodel Dossou", position: "FORWARD", number: 11 },
  { teamCode: "BEN", name: "Mohamed Tijani", position: "FORWARD", number: 10 },
  { teamCode: "BEN", name: "Junior Olaïtan", position: "FORWARD", number: 7 },
  { teamCode: "BEN", name: "Mama Seibou", position: "MIDFIELDER", number: 18 },
  { teamCode: "BEN", name: "Rachid Moumini", position: "MIDFIELDER", number: 17 },
  { teamCode: "BEN", name: "Youssouf Assogba", position: "DEFENDER", number: 12 },
  { teamCode: "BEN", name: "Stéphane Sessègnon", position: "MIDFIELDER", number: 13 },

  // ========== GROUPE F - BURKINA FASO ==========
  { teamCode: "BFA", name: "Hervé Koffi", position: "GOALKEEPER", number: 16 },
  { teamCode: "BFA", name: "Farid Ouédraogo", position: "GOALKEEPER", number: 1 },
  { teamCode: "BFA", name: "Killian Nikiéma", position: "GOALKEEPER", number: 23 },
  { teamCode: "BFA", name: "Steeve Yago", position: "DEFENDER", number: 14 },
  { teamCode: "BFA", name: "Issoufou Dayo", position: "DEFENDER", number: 12 },
  { teamCode: "BFA", name: "Edmond Tapsoba", position: "DEFENDER", number: 3 },
  { teamCode: "BFA", name: "Issa Kaboré", position: "DEFENDER", number: 9 },
  { teamCode: "BFA", name: "Adamo Nagalo", position: "DEFENDER", number: 4 },
  { teamCode: "BFA", name: "Ibrahim Blati Touré", position: "MIDFIELDER", number: 6 },
  { teamCode: "BFA", name: "Blati Touré", position: "MIDFIELDER", number: 17 },
  { teamCode: "BFA", name: "Gustavo Sangaré", position: "MIDFIELDER", number: 22 },
  { teamCode: "BFA", name: "Sacha Bansé", position: "MIDFIELDER", number: 8 },
  { teamCode: "BFA", name: "Bertrand Traoré", position: "FORWARD", number: 10 },
  { teamCode: "BFA", name: "Dango Ouattara", position: "FORWARD", number: 7 },
  { teamCode: "BFA", name: "Mohamed Konaté", position: "FORWARD", number: 19 },
  { teamCode: "BFA", name: "Abdoul Tapsoba", position: "FORWARD", number: 18 },
  { teamCode: "BFA", name: "Hassane Bandé", position: "FORWARD", number: 20 },
  { teamCode: "BFA", name: "Cédric Badolo", position: "FORWARD", number: 11 },
  { teamCode: "BFA", name: "Dramane Salou", position: "MIDFIELDER", number: 13 },
  { teamCode: "BFA", name: "Apollinaire Bamba", position: "DEFENDER", number: 5 },
  { teamCode: "BFA", name: "Ismahila Ouédraogo", position: "MIDFIELDER", number: 15 },

  // ========== GROUPE F - GABON ==========
  { teamCode: "GAB", name: "Jean-Noël Amonome", position: "GOALKEEPER", number: 1 },
  { teamCode: "GAB", name: "Anthony Mfa Mezui", position: "GOALKEEPER", number: 16 },
  { teamCode: "GAB", name: "Loyce Mbaba", position: "GOALKEEPER", number: 23 },
  { teamCode: "GAB", name: "Aaron Appindangoyé", position: "DEFENDER", number: 2 },
  { teamCode: "GAB", name: "Sidney Obissa", position: "DEFENDER", number: 5 },
  { teamCode: "GAB", name: "Bruno Ecuele Manga", position: "DEFENDER", number: 4 },
  { teamCode: "GAB", name: "Johann Obiang", position: "DEFENDER", number: 3 },
  { teamCode: "GAB", name: "Lloyd Palun", position: "DEFENDER", number: 12 },
  { teamCode: "GAB", name: "Guélor Kanga", position: "MIDFIELDER", number: 8 },
  { teamCode: "GAB", name: "Mario Lemina", position: "MIDFIELDER", number: 6 },
  { teamCode: "GAB", name: "Didier Ndong", position: "MIDFIELDER", number: 18 },
  { teamCode: "GAB", name: "Alex Moucketou-Moussounda", position: "MIDFIELDER", number: 14 },
  { teamCode: "GAB", name: "Pierre-Emerick Aubameyang", position: "FORWARD", number: 9 },
  { teamCode: "GAB", name: "Denis Bouanga", position: "FORWARD", number: 20 },
  { teamCode: "GAB", name: "Jim Allevinah", position: "FORWARD", number: 11 },
  { teamCode: "GAB", name: "Aaron Boupendza", position: "FORWARD", number: 13 },
  { teamCode: "GAB", name: "Axel Méyé", position: "FORWARD", number: 7 },
  { teamCode: "GAB", name: "Shavy Babicka", position: "FORWARD", number: 17 },
  { teamCode: "GAB", name: "David Sambissa", position: "MIDFIELDER", number: 10 },
  { teamCode: "GAB", name: "Ulrick Eneme-Ella", position: "DEFENDER", number: 19 },
  { teamCode: "GAB", name: "Medwin Biteghe", position: "MIDFIELDER", number: 15 },

  // ========== GROUPE F - OUGANDA ==========
  { teamCode: "UGA", name: "Ismail Watenga", position: "GOALKEEPER", number: 1 },
  { teamCode: "UGA", name: "Salim Magoola", position: "GOALKEEPER", number: 18 },
  { teamCode: "UGA", name: "Charles Lukwago", position: "GOALKEEPER", number: 16 },
  { teamCode: "UGA", name: "Bevis Mugabi", position: "DEFENDER", number: 4 },
  { teamCode: "UGA", name: "Halid Lwaliwa", position: "DEFENDER", number: 12 },
  { teamCode: "UGA", name: "Kenneth Semakula", position: "DEFENDER", number: 2 },
  { teamCode: "UGA", name: "Aziz Kayondo", position: "DEFENDER", number: 3 },
  { teamCode: "UGA", name: "Elvis Bwomono", position: "DEFENDER", number: 20 },
  { teamCode: "UGA", name: "Khalid Aucho", position: "MIDFIELDER", number: 8 },
  { teamCode: "UGA", name: "Bobosi Byaruhanga", position: "MIDFIELDER", number: 6 },
  { teamCode: "UGA", name: "Moses Waiswa", position: "MIDFIELDER", number: 13 },
  { teamCode: "UGA", name: "Travis Mutyaba", position: "MIDFIELDER", number: 17 },
  { teamCode: "UGA", name: "Emmanuel Okwi", position: "FORWARD", number: 9 },
  { teamCode: "UGA", name: "Fahad Bayo", position: "FORWARD", number: 19 },
  { teamCode: "UGA", name: "Steven Mukwala", position: "FORWARD", number: 11 },
  { teamCode: "UGA", name: "Martin Kizza", position: "FORWARD", number: 7 },
  { teamCode: "UGA", name: "Yunus Sentamu", position: "FORWARD", number: 10 },
  { teamCode: "UGA", name: "Milton Karisa", position: "FORWARD", number: 15 },
  { teamCode: "UGA", name: "Rogers Mato", position: "MIDFIELDER", number: 14 },
  { teamCode: "UGA", name: "Abdu Lumala", position: "FORWARD", number: 21 },
  { teamCode: "UGA", name: "Denis Omedi", position: "FORWARD", number: 22 },

  // ========== GROUPE F - BOTSWANA ==========
  { teamCode: "BOT", name: "Kabelo Dambe", position: "GOALKEEPER", number: 16 },
  { teamCode: "BOT", name: "Ezekiel Morake", position: "GOALKEEPER", number: 1 },
  { teamCode: "BOT", name: "Goitseone Phoko", position: "GOALKEEPER", number: 23 },
  { teamCode: "BOT", name: "Thatayaone Ditlhokwe", position: "DEFENDER", number: 4 },
  { teamCode: "BOT", name: "Mosha Gaolaolwe", position: "DEFENDER", number: 5 },
  { teamCode: "BOT", name: "Tshepo Maikano", position: "DEFENDER", number: 3 },
  { teamCode: "BOT", name: "Tebogo Kopelang", position: "DEFENDER", number: 2 },
  { teamCode: "BOT", name: "Benson Mangolo", position: "DEFENDER", number: 13 },
  { teamCode: "BOT", name: "Kabelo Seakanyeng", position: "MIDFIELDER", number: 8 },
  { teamCode: "BOT", name: "Gape Mohutsiwa", position: "MIDFIELDER", number: 6 },
  { teamCode: "BOT", name: "Thero Setsile", position: "MIDFIELDER", number: 10 },
  { teamCode: "BOT", name: "Baokeditswe Talane", position: "MIDFIELDER", number: 15 },
  { teamCode: "BOT", name: "Tumisang Orebonye", position: "FORWARD", number: 9 },
  { teamCode: "BOT", name: "Kabelo Dambe", position: "FORWARD", number: 11 },
  { teamCode: "BOT", name: "Thabang Sesinyi", position: "FORWARD", number: 7 },
  { teamCode: "BOT", name: "Terrence Mandaza", position: "FORWARD", number: 14 },
  { teamCode: "BOT", name: "Lemogang Maswena", position: "FORWARD", number: 19 },
  { teamCode: "BOT", name: "Gilbert Baruti", position: "MIDFIELDER", number: 12 },
  { teamCode: "BOT", name: "Godfrey Tauyatswala", position: "MIDFIELDER", number: 17 },
  { teamCode: "BOT", name: "Seamolo Modingwane", position: "DEFENDER", number: 18 },
];

export async function seedPlayers() {
  console.log("⚽ Seeding players...");

  // First, get all teams in one query
  const teams = await prisma.team.findMany();
  const teamCodeToId = new Map(teams.map((t) => [t.code, t.id]));

  // Delete existing players for clean seed
  console.log("   Cleaning existing players...");
  await prisma.player.deleteMany({});

  // Prepare player data with team IDs
  const playersToCreate = players
    .map((playerData) => {
      const teamId = teamCodeToId.get(playerData.teamCode);
      if (!teamId) {
        console.error(`❌ Team not found: ${playerData.teamCode}`);
        return null;
      }
      return {
        teamId,
        name: playerData.name,
        nameFr: playerData.name,
        position: playerData.position,
        number: playerData.number,
      };
    })
    .filter((p) => p !== null);

  // Batch create players (Prisma's createMany is much faster)
  console.log(`   Creating ${playersToCreate.length} players...`);
  await prisma.player.createMany({
    data: playersToCreate,
    skipDuplicates: true,
  });

  console.log(`✅ ${playersToCreate.length} players seeded successfully!`);
  console.log(`   Total: ${players.length} players across 24 teams`);
}

// Execute if run directly
if (require.main === module) {
  seedPlayers()
    .then(() => {
      console.log("✅ Players seed completed!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("❌ Error seeding players:", error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
