export type ProductVariant = {
  option1Name?: string;
  option1Value?: string;
  option2Name?: string;
  option2Value?: string;
  price: number;
};

export type Product = {
  handle: string;
  sku: string;
  name: string;
  category: string;
  description?: string;
  price?: number;
  variants?: ProductVariant[];
  isModifier?: boolean;
  hasTax?: boolean;
  image?: string; // Chemin de l'image dans /images/menu-items/
};

export const menuProducts: Product[] = [
  // Boissons - Cafés
  {
    handle: "espresso",
    sku: "ESP-001",
    name: "Espresso",
    category: "Boissons - Cafés",
    description: "Café espresso classique",
    price: 15,
  },
  {
    handle: "espresso-double",
    sku: "ESP-002",
    name: "Double Espresso",
    category: "Boissons - Cafés",
    description: "Double dose d'espresso",
    price: 20,
  },
  {
    handle: "ristretto",
    sku: "RIS-001",
    name: "Ristretto",
    category: "Boissons - Cafés",
    description: "Espresso court et concentré",
    price: 18,
  },
  {
    handle: "lungo",
    sku: "LUN-001",
    name: "Long / Lungo",
    category: "Boissons - Cafés",
    description: "Espresso allongé",
    price: 20,
  },
  {
    handle: "americano-chaud",
    sku: "AME-001",
    name: "Americano Chaud",
    category: "Boissons - Cafés",
    description: "Espresso allongé eau chaude",
    price: 20,
  },
  {
    handle: "americano-froid",
    sku: "AME-002",
    name: "Americano Froid",
    category: "Boissons - Cafés",
    description: "Espresso servi froid",
    price: 30,
  },
  {
    handle: "cafe-glace",
    sku: "ICE-001",
    name: "Café Glacé",
    category: "Boissons - Cafés",
    description: "Café froid avec glaçons",
    price: 30,
  },

  // Boissons - Boissons Lactées
  {
    handle: "iced-latte",
    sku: "ICL-001",
    name: "Iced Latte",
    category: "Boissons - Boissons Lactées",
    description: "Espresso avec lait froid",
    price: 35,
  },
  {
    handle: "latte",
    sku: "LAT",
    name: "Latte",
    category: "Boissons - Boissons Lactées",
    description: "Espresso avec lait chaud",
    variants: [
      { option1Name: "Taille", option1Value: "Small", price: 20 },
      { option1Name: "Taille", option1Value: "Medium", price: 30 },
      { option1Name: "Taille", option1Value: "Large", price: 40 },
    ],
  },
  {
    handle: "cappuccino",
    sku: "CAP",
    name: "Cappuccino",
    category: "Boissons - Boissons Lactées",
    description: "Espresso avec mousse de lait",
    variants: [
      { option1Name: "Taille", option1Value: "Small", price: 25 },
      { option1Name: "Taille", option1Value: "Medium", price: 35 },
      { option1Name: "Taille", option1Value: "Large", price: 45 },
    ],
  },
  {
    handle: "flat-white",
    sku: "FLW-001",
    name: "Flat White",
    category: "Boissons - Boissons Lactées",
    description: "Espresso micro-mousse",
    price: 30,
  },
  {
    handle: "macchiato",
    sku: "MAC-001",
    name: "Macchiato",
    category: "Boissons - Boissons Lactées",
    description: "Espresso marqué lait",
    price: 22,
  },
  {
    handle: "cortado",
    sku: "COR-001",
    name: "Cortado",
    category: "Boissons - Boissons Lactées",
    description: "Espresso coupé lait",
    price: 25,
  },
  {
    handle: "cafe-au-lait",
    sku: "CAL-001",
    name: "Café au Lait",
    category: "Boissons - Boissons Lactées",
    description: "Café avec lait",
    price: 25,
  },
  {
    handle: "cold-brew",
    sku: "COL-001",
    name: "Cold Brew",
    category: "Boissons - Boissons Lactées",
    description: "Café infusé froid",
    price: 35,
  },
  {
    handle: "frappe-cafe",
    sku: "FRA-001",
    name: "Frappé Café",
    category: "Boissons - Boissons Lactées",
    description: "Café mixé glace",
    price: 40,
  },
  {
    handle: "lait-chaud",
    sku: "LCH",
    name: "Lait Chaud Simple",
    category: "Boissons - Boissons Lactées",
    description: "Lait chaud nature",
    variants: [
      { option1Name: "Taille", option1Value: "Small", price: 20 },
      { option1Name: "Taille", option1Value: "Medium", price: 30 },
    ],
  },
  {
    handle: "lait-chaud-arome",
    sku: "LCA",
    name: "Lait Chaud Aromatisé",
    category: "Boissons - Boissons Lactées",
    description: "Lait chaud sirop",
    variants: [
      { option1Name: "Taille", option1Value: "Small", price: 25 },
      { option1Name: "Taille", option1Value: "Medium", price: 35 },
    ],
  },
  {
    handle: "lait-froid",
    sku: "LFR-001",
    name: "Lait Froid Simple",
    category: "Boissons - Boissons Lactées",
    description: "Lait froid nature",
    price: 30,
  },
  {
    handle: "lait-froid-arome",
    sku: "LFA-001",
    name: "Lait Froid Aromatisé",
    category: "Boissons - Boissons Lactées",
    description: "Lait froid sirop",
    price: 35,
  },

  // Boissons - Milkshakes
  {
    handle: "milkshake-vanille",
    sku: "MSV-001",
    name: "Milkshake Vanille",
    category: "Boissons - Milkshakes",
    description: "Milkshake vanille",
    price: 45,
  },
  {
    handle: "milkshake-chocolat",
    sku: "MSC-001",
    name: "Milkshake Chocolat",
    category: "Boissons - Milkshakes",
    description: "Milkshake chocolat",
    price: 45,
  },
  {
    handle: "milkshake-fraise",
    sku: "MSF-001",
    name: "Milkshake Fraise",
    category: "Boissons - Milkshakes",
    description: "Milkshake fraise",
    price: 50,
  },

  // Boissons - Spécialisées
  {
    handle: "chocolat-chaud",
    sku: "CHO-001",
    name: "Chocolat Chaud",
    category: "Boissons - Spécialisées",
    description: "Chocolat chaud",
    price: 30,
  },
  {
    handle: "chocolat-froid",
    sku: "CHF-001",
    name: "Chocolat Froid",
    category: "Boissons - Spécialisées",
    description: "Chocolat froid",
    price: 35,
  },
  {
    handle: "chocolat-blanc",
    sku: "CHB",
    name: "Chocolat Blanc",
    category: "Boissons - Spécialisées",
    description: "Chocolat blanc",
    variants: [
      { option1Name: "Température", option1Value: "Chaud", price: 35 },
      { option1Name: "Température", option1Value: "Froid", price: 35 },
    ],
  },
  {
    handle: "matcha-latte",
    sku: "MAT",
    name: "Matcha Latte",
    category: "Boissons - Spécialisées",
    description: "Latte matcha",
    variants: [
      { option1Name: "Température", option1Value: "Chaud", price: 40 },
      { option1Name: "Température", option1Value: "Froid", price: 40 },
    ],
  },
  {
    handle: "chai-latte",
    sku: "CHA",
    name: "Chai Latte",
    category: "Boissons - Spécialisées",
    description: "Latte chai",
    variants: [
      { option1Name: "Température", option1Value: "Chaud", price: 40 },
      { option1Name: "Température", option1Value: "Froid", price: 40 },
    ],
  },
  {
    handle: "white-mocha",
    sku: "WMO-001",
    name: "White Mocha",
    category: "Boissons - Spécialisées",
    description: "Latte chocolat blanc",
    price: 45,
  },

  // Desserts
  {
    handle: "gaufre-classique",
    sku: "GAU-CLA",
    name: "Gaufre Classique",
    category: "Desserts",
    description: "Gaufre croustillante",
    price: 35,
  },
  {
    handle: "gaufre-tiramisu",
    sku: "GAU-TIR",
    name: "Gaufre Tiramisu",
    category: "Desserts",
    description: "Gaufre tiramisu",
    price: 55,
  },
  {
    handle: "pancake-tiramisu",
    sku: "PAN-TIR",
    name: "Pancake Tiramisu",
    category: "Desserts",
    description: "Pancakes tiramisu",
    price: 55,
  },
  {
    handle: "brioche-tiramisu",
    sku: "BRI-TIR",
    name: "Brioche Tiramisu",
    category: "Desserts",
    description: "Brioche tiramisu",
    price: 60,
  },
  {
    handle: "bubble-tiramisu",
    sku: "BUB-TIR",
    name: "Bubble Waffle Tiramisu",
    category: "Desserts",
    description: "Bubble tiramisu",
    price: 65,
  },
  {
    handle: "craffle-tiramisu",
    sku: "CRA-TIR",
    name: "Craffle Tiramisu",
    category: "Desserts",
    description: "Craffle tiramisu",
    price: 60,
  },

  // Desserts - Cans
  {
    handle: "can-dubai",
    sku: "CAN-DUB",
    name: "Can Façon Dubai",
    category: "Desserts - Cans",
    description: "Canette Dubai",
    price: 60,
  },
  {
    handle: "can-fraise-choco",
    sku: "CAN-FCP",
    name: "Can Fraise Choco Pistache",
    category: "Desserts - Cans",
    description: "Canette trio",
    price: 65,
  },
  {
    handle: "ticanmisu",
    sku: "TIC",
    name: "Ticanmisu",
    category: "Desserts - Cans",
    description: "Canette tiramisu",
    variants: [
      { option1Name: "Saveur", option1Value: "Oreo", price: 55 },
      { option1Name: "Saveur", option1Value: "Caramel", price: 55 },
      { option1Name: "Saveur", option1Value: "Daim", price: 55 },
      { option1Name: "Saveur", option1Value: "M&M's", price: 55 },
      { option1Name: "Saveur", option1Value: "Kinder Bueno", price: 60 },
      { option1Name: "Saveur", option1Value: "Nutella", price: 60 },
      { option1Name: "Saveur", option1Value: "Mangue", price: 55 },
      { option1Name: "Saveur", option1Value: "Fraise", price: 55 },
    ],
  },

  // Briodogs Salés
  {
    handle: "brio-classic",
    sku: "BDG-CLA",
    name: "BriO'Classic",
    category: "Briodogs Salés",
    description: "Briodog saucisse",
    price: 60,
  },
  {
    handle: "brio-savoyard",
    sku: "BDG-SAV",
    name: "BriO'Savoyard",
    category: "Briodogs Salés",
    description: "Briodog Reblochon",
    price: 65,
  },
  {
    handle: "brio-lyonnais",
    sku: "BDG-LYO",
    name: "BriO'Lyonnais",
    category: "Briodogs Salés",
    description: "Briodog Saint-Marcellin",
    price: 65,
  },
  {
    handle: "brio-veggie",
    sku: "BDG-VEG",
    name: "BriO'Veggie",
    category: "Briodogs Salés",
    description: "Briodog végétarien",
    price: 60,
  },
  {
    handle: "brio-italiano",
    sku: "BDG-ITA",
    name: "BriO'Italiano",
    category: "Briodogs Salés",
    description: "Briodog mozzarella",
    price: 65,
  },
  {
    handle: "brio-malay",
    sku: "BDG-MAL",
    name: "BriO'Malay",
    category: "Briodogs Salés",
    description: "Briodog rendang",
    price: 70,
  },
  {
    handle: "brio-indien",
    sku: "BDG-IND",
    name: "Brio Indien",
    category: "Briodogs Salés",
    description: "Briodog tandoori",
    price: 70,
  },
  {
    handle: "brio-falafel",
    sku: "BDG-FAL",
    name: "BriO'Falafel",
    category: "Briodogs Salés",
    description: "Briodog falafels",
    price: 60,
  },

  // Briodogs Sucrés
  {
    handle: "brio-caramel",
    sku: "BDG-CAR",
    name: "Brio'Caramel",
    category: "Briodogs Sucrés",
    description: "Briodog caramel",
    price: 50,
  },
  {
    handle: "brio-choco-banane",
    sku: "BDG-CHB",
    name: "Brio'Choco-Banane",
    category: "Briodogs Sucrés",
    description: "Briodog chocolat",
    price: 50,
  },
  {
    handle: "brio-pomme",
    sku: "BDG-POM",
    name: "Brio'Pomme-Cannelle",
    category: "Briodogs Sucrés",
    description: "Briodog pommes",
    price: 50,
  },
  {
    handle: "brio-fraises",
    sku: "BDG-FRA",
    name: "Brio'Fraises",
    category: "Briodogs Sucrés",
    description: "Briodog fraises",
    price: 50,
  },
  {
    handle: "brio-amlou",
    sku: "BDG-AML",
    name: "Brio'Amlou",
    category: "Briodogs Sucrés",
    description: "Briodog Amlou",
    price: 50,
  },
  {
    handle: "brio-coco",
    sku: "BDG-COC",
    name: "Brio'Coco-Tropical",
    category: "Briodogs Sucrés",
    description: "Briodog coco",
    price: 50,
  },

  // Modificateurs - Toppings Sucrés
  {
    handle: "topping-choco",
    sku: "TOP-CHO",
    name: "Topping Chocolat",
    category: "Modificateurs",
    description: "Sauce chocolat",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-caramel",
    sku: "TOP-CAR",
    name: "Topping Caramel",
    category: "Modificateurs",
    description: "Sauce caramel",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-oreo",
    sku: "TOP-ORE",
    name: "Topping Oreo",
    category: "Modificateurs",
    description: "Biscuits Oreo",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-amandes",
    sku: "TOP-AMD",
    name: "Topping Amandes",
    category: "Modificateurs",
    description: "Amandes",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-noisettes",
    sku: "TOP-NOI",
    name: "Topping Noisettes",
    category: "Modificateurs",
    description: "Noisettes",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-speculoos",
    sku: "TOP-SPE",
    name: "Topping Speculoos",
    category: "Modificateurs",
    description: "Biscuits speculoos",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-fruits",
    sku: "TOP-FRU",
    name: "Topping Fruits Rouges",
    category: "Modificateurs",
    description: "Fruits rouges",
    price: 12,
    isModifier: true,
  },
  {
    handle: "topping-fraises",
    sku: "TOP-FRA",
    name: "Topping Fraises",
    category: "Modificateurs",
    description: "Fraises",
    price: 12,
    isModifier: true,
  },
  {
    handle: "topping-banane",
    sku: "TOP-BAN",
    name: "Topping Banane",
    category: "Modificateurs",
    description: "Banane",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-kiwi",
    sku: "TOP-KIW",
    name: "Topping Kiwi",
    category: "Modificateurs",
    description: "Kiwi",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-smarties",
    sku: "TOP-SMA",
    name: "Topping Smarties",
    category: "Modificateurs",
    description: "Smarties",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-mnm",
    sku: "TOP-MNM",
    name: "Topping M&M's",
    category: "Modificateurs",
    description: "M&M's",
    price: 10,
    isModifier: true,
  },
  {
    handle: "topping-nutella",
    sku: "TOP-NUT",
    name: "Topping Nutella",
    category: "Modificateurs",
    description: "Nutella",
    price: 12,
    isModifier: true,
  },
  {
    handle: "topping-lotus",
    sku: "TOP-LOT",
    name: "Topping Lotus",
    category: "Modificateurs",
    description: "Lotus",
    price: 12,
    isModifier: true,
  },
  {
    handle: "topping-miel",
    sku: "TOP-MIE",
    name: "Topping Miel",
    category: "Modificateurs",
    description: "Miel",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-coco",
    sku: "TOP-COC",
    name: "Topping Coco",
    category: "Modificateurs",
    description: "Coco râpée",
    price: 8,
    isModifier: true,
  },
  {
    handle: "topping-pistache",
    sku: "TOP-PIS",
    name: "Topping Pistaches",
    category: "Modificateurs",
    description: "Pistaches",
    price: 12,
    isModifier: true,
  },
  {
    handle: "topping-framboises",
    sku: "TOP-FRM",
    name: "Topping Framboises",
    category: "Modificateurs",
    description: "Framboises",
    price: 12,
    isModifier: true,
  },

  // Modificateurs - Sauces
  {
    handle: "sauce-moutarde",
    sku: "SAU-MMI",
    name: "Sauce Moutarde-Miel",
    category: "Modificateurs",
    description: "Moutarde miel",
    price: 5,
    isModifier: true,
  },
  {
    handle: "sauce-ketchup",
    sku: "SAU-KET",
    name: "Sauce Ketchup",
    category: "Modificateurs",
    description: "Ketchup",
    price: 3,
    isModifier: true,
  },
  {
    handle: "sauce-mayo",
    sku: "SAU-MAY",
    name: "Sauce Mayo",
    category: "Modificateurs",
    description: "Mayo",
    price: 3,
    isModifier: true,
  },
  {
    handle: "sauce-bbq",
    sku: "SAU-BBQ",
    name: "Sauce BBQ",
    category: "Modificateurs",
    description: "BBQ",
    price: 5,
    isModifier: true,
  },
  {
    handle: "sauce-pesto",
    sku: "SAU-PES",
    name: "Sauce Pesto",
    category: "Modificateurs",
    description: "Pesto",
    price: 8,
    isModifier: true,
  },
  {
    handle: "sauce-harissa",
    sku: "SAU-HAR",
    name: "Sauce Harissa",
    category: "Modificateurs",
    description: "Harissa",
    price: 5,
    isModifier: true,
  },
  {
    handle: "sauce-andalouse",
    sku: "SAU-AND",
    name: "Sauce Andalouse",
    category: "Modificateurs",
    description: "Andalouse",
    price: 5,
    isModifier: true,
  },

  // Modificateurs - Fromages
  {
    handle: "fromage-cheddar",
    sku: "FRO-CHE",
    name: "Fromage Cheddar",
    category: "Modificateurs",
    description: "Cheddar",
    price: 8,
    isModifier: true,
  },
  {
    handle: "fromage-mozzarella",
    sku: "FRO-MOZ",
    name: "Fromage Mozzarella",
    category: "Modificateurs",
    description: "Mozzarella",
    price: 8,
    isModifier: true,
  },

  // Modificateurs - Extras
  {
    handle: "oignons-caramelises",
    sku: "EXT-OIG",
    name: "Oignons Caramélisés",
    category: "Modificateurs",
    description: "Oignons",
    price: 5,
    isModifier: true,
  },
  {
    handle: "extra-saucisse",
    sku: "EXT-SAU",
    name: "Saucisse Extra",
    category: "Modificateurs",
    description: "Saucisse extra",
    price: 15,
    isModifier: true,
  },
  {
    handle: "extra-falafel",
    sku: "EXT-FAL",
    name: "Falafel Extra",
    category: "Modificateurs",
    description: "Falafel extra",
    price: 10,
    isModifier: true,
  },
  {
    handle: "shot-espresso",
    sku: "EXT-ESP",
    name: "Shot Espresso",
    category: "Modificateurs",
    description: "Shot espresso",
    price: 8,
    isModifier: true,
  },
  {
    handle: "lait-vegetal",
    sku: "EXT-VEG",
    name: "Lait Végétal",
    category: "Modificateurs",
    description: "Lait végétal",
    isModifier: true,
    variants: [
      { option1Name: "Type", option1Value: "Soja", price: 5 },
      { option1Name: "Type", option1Value: "Amande", price: 5 },
      { option1Name: "Type", option1Value: "Avoine", price: 5 },
      { option1Name: "Type", option1Value: "Coco", price: 5 },
    ],
  },
  {
    handle: "creme-fouettee",
    sku: "EXT-CRE",
    name: "Crème Fouettée",
    category: "Modificateurs",
    description: "Crème fouettée",
    price: 8,
    isModifier: true,
  },

  // Modificateurs - Glaces
  {
    handle: "glace-vanille",
    sku: "EXT-GLV",
    name: "Glace Vanille",
    category: "Modificateurs",
    description: "Glace vanille",
    price: 10,
    isModifier: true,
  },
  {
    handle: "glace-choco-lait",
    sku: "EXT-GCL",
    name: "Glace Chocolat Lait",
    category: "Modificateurs",
    description: "Glace choco lait",
    price: 10,
    isModifier: true,
  },
  {
    handle: "glace-choco-noir",
    sku: "EXT-GCN",
    name: "Glace Chocolat Noir",
    category: "Modificateurs",
    description: "Glace choco noir",
    price: 10,
    isModifier: true,
  },
  {
    handle: "glace-fraise",
    sku: "EXT-GLF",
    name: "Glace Fraise",
    category: "Modificateurs",
    description: "Glace fraise",
    price: 12,
    isModifier: true,
  },
  {
    handle: "glace-pistache",
    sku: "EXT-GPI",
    name: "Glace Pistache",
    category: "Modificateurs",
    description: "Glace pistache",
    price: 15,
    isModifier: true,
  },
  {
    handle: "glace-ruby",
    sku: "EXT-GRU",
    name: "Glace Ruby Framboise",
    category: "Modificateurs",
    description: "Glace ruby",
    price: 15,
    isModifier: true,
  },
  {
    handle: "glace-mangue",
    sku: "EXT-GMA",
    name: "Glace Mangue",
    category: "Modificateurs",
    description: "Glace mangue",
    price: 12,
    isModifier: true,
  },
  {
    handle: "glace-raffaelo",
    sku: "EXT-GRA",
    name: "Glace Raffaelo",
    category: "Modificateurs",
    description: "Glace Raffaelo",
    price: 15,
    isModifier: true,
  },
  {
    handle: "option-chantilly",
    sku: "OPT-CHA",
    name: "Option Chantilly",
    category: "Modificateurs",
    description: "Chantilly",
    price: 8,
    isModifier: true,
  },
  {
    handle: "option-fraise",
    sku: "OPT-FRA",
    name: "Option Fraise Can",
    category: "Modificateurs",
    description: "Ajout fraise",
    price: 10,
    isModifier: true,
  },

  // Boissons - Extras (Sirops)
  {
    handle: "sirop-extra",
    sku: "SIR",
    name: "Sirop Supplément",
    category: "Boissons - Extras",
    description: "Shot sirop",
    isModifier: true,
    variants: [
      { option1Name: "Parfum", option1Value: "Vanille", price: 5 },
      { option1Name: "Parfum", option1Value: "Caramel", price: 5 },
      { option1Name: "Parfum", option1Value: "Noisette", price: 5 },
      { option1Name: "Parfum", option1Value: "Autre", price: 10 },
    ],
  },

  // Shots Vitaminés
  {
    handle: "shot-gingembre",
    sku: "SHOT-GIN",
    name: "Shot Gingembre Citron Pomme",
    category: "Shots Vitaminés",
    description: "Boost immunitaire : pomme citron gingembre miel",
    price: 25,
    image: "shot-gingembre.jpg",
  },
  {
    handle: "shot-lait-or",
    sku: "SHOT-LOR",
    name: "Shot Lait d'Or",
    category: "Shots Vitaminés",
    description: "Golden milk : lait coco curcuma gingembre cannelle",
    price: 28,
    image: "shot-lait-or.jpg",
  },
  {
    handle: "shot-wheatgrass",
    sku: "SHOT-WHE",
    name: "Shot Wheatgrass",
    category: "Shots Vitaminés",
    description: "Détox : herbe de blé pomme citron spiruline",
    price: 30,
    image: "shot-wheatgrass.jpg",
  },
  {
    handle: "shot-orange-curcuma",
    sku: "SHOT-ORA",
    name: "Shot Orange Curcuma Carotte",
    category: "Shots Vitaminés",
    description: "Vitamine C : orange carotte curcuma gingembre",
    price: 25,
    image: "shot-orange-curcuma.jpg",
  },
  {
    handle: "shot-acai",
    sku: "SHOT-ACA",
    name: "Shot Açaí Antioxydant",
    category: "Shots Vitaminés",
    description: "Antioxydants : açaí myrtilles grenade",
    price: 32,
    image: "shot-acai.jpg",
  },
  {
    handle: "shot-vert-detox",
    sku: "SHOT-VER",
    name: "Shot Vert Détox",
    category: "Shots Vitaminés",
    description: "Détox : concombre céleri citron menthe spiruline",
    price: 28,
    image: "shot-vert-detox.jpg",
  },
  {
    handle: "shot-betterave",
    sku: "SHOT-BET",
    name: "Shot Betterave Boost",
    category: "Shots Vitaminés",
    description: "Énergie : betterave pomme citron gingembre",
    price: 26,
    image: "shot-betterave.jpg",
  },
  {
    handle: "shot-coco-ananas",
    sku: "SHOT-COC",
    name: "Shot Coco Ananas Immuno",
    category: "Shots Vitaminés",
    description: "Immunité : eau coco ananas citron gingembre",
    price: 27,
    image: "shot-coco-ananas.jpg",
  },
  {
    handle: "shot-cayenne",
    sku: "SHOT-CAY",
    name: "Shot Cayenne Fire",
    category: "Shots Vitaminés",
    description: "Métabolisme : citron sirop érable cayenne",
    price: 24,
    image: "shot-cayenne.jpg",
  },
  {
    handle: "shot-proteine",
    sku: "SHOT-PRO",
    name: "Shot Protéine Verte",
    category: "Shots Vitaminés",
    description: "Protéines : lait amande spiruline épinards chia",
    price: 35,
    image: "shot-proteine.jpg",
  },
  {
    handle: "shot-citron-menthe",
    sku: "SHOT-CIT",
    name: "Shot Citron Gingembre Menthe",
    category: "Shots Vitaminés",
    description: "Digestion : citron gingembre menthe miel",
    price: 22,
    image: "shot-citron-menthe.jpg",
  },
  {
    handle: "shot-mangue-curcuma",
    sku: "SHOT-MAN",
    name: "Shot Mangue Curcuma Tropical",
    category: "Shots Vitaminés",
    description: "Tropical : mangue orange curcuma lait coco",
    price: 28,
    image: "shot-mangue-curcuma.jpg",
  },

  // Eaux & Soft Drinks
  {
    handle: "oulmes",
    sku: "OULM",
    name: "Oulmes",
    category: "Eaux & Soft Drinks",
    description: "Eau minérale naturellement gazeuse",
    image: "oulmes.jpg",
    variants: [
      { option1Name: "Format", option1Value: "25cl verre", price: 10 },
      { option1Name: "Format", option1Value: "33cl", price: 8 },
      { option1Name: "Format", option1Value: "1L", price: 15 },
    ],
  },
  {
    handle: "oulmes-orange",
    sku: "OULM-ORA",
    name: "Oulmes Bulles Fruitées Orange",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse jus orange naturel 25cl verre",
    price: 12,
    image: "oulmes-orange.jpg",
  },
  {
    handle: "oulmes-citron",
    sku: "OULM-CIT",
    name: "Oulmes Bulles Fruitées Citron",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse jus citron naturel 25cl verre",
    price: 12,
    image: "oulmes-citron.jpg",
  },
  {
    handle: "oulmes-tropical",
    sku: "OULM-TRO",
    name: "Oulmes Bulles Fruitées Tropical",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse jus fruits tropical 25cl verre",
    price: 12,
    image: "oulmes-tropical.jpg",
  },
  {
    handle: "oulmes-mojito",
    sku: "OULM-MOJ",
    name: "Oulmes Bulles Fruitées Mojito",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse saveur mojito menthe 25cl verre",
    price: 12,
    image: "oulmes-mojito.jpg",
  },
  {
    handle: "oulmes-pinacolada",
    sku: "OULM-PIN",
    name: "Oulmes Bulles Fruitées Piña Colada",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse saveur piña colada 25cl verre",
    price: 12,
    image: "oulmes-pinacolada.jpg",
  },
  {
    handle: "oulmes-fruits-rouges",
    sku: "OULM-FRU",
    name: "Oulmes Bulles Fruitées Fruits Rouges",
    category: "Eaux & Soft Drinks",
    description: "Eau gazeuse fruits rouges 25cl verre",
    price: 12,
    image: "oulmes-fruits-rouges.jpg",
  },
  {
    handle: "glass-cola",
    sku: "GLASS-COL",
    name: "Glass' Cola",
    category: "Eaux & Soft Drinks",
    description: "Boisson gazeuse cola",
    image: "glass-cola.jpg",
    variants: [
      { option1Name: "Format", option1Value: "33cl", price: 8 },
      { option1Name: "Format", option1Value: "1.5L", price: 15 },
    ],
  },
  {
    handle: "glass-tropical",
    sku: "GLASS-TRO",
    name: "Glass' Tropical",
    category: "Eaux & Soft Drinks",
    description: "Boisson gazeuse tropical",
    image: "glass-tropical.jpg",
    variants: [
      { option1Name: "Format", option1Value: "33cl", price: 8 },
      { option1Name: "Format", option1Value: "1.5L", price: 15 },
    ],
  },
  {
    handle: "glass-pomme",
    sku: "GLASS-POM",
    name: "Glass' Pomme",
    category: "Eaux & Soft Drinks",
    description: "Boisson gazeuse pomme",
    image: "glass-pomme.jpg",
    variants: [
      { option1Name: "Format", option1Value: "33cl", price: 8 },
      { option1Name: "Format", option1Value: "1.5L", price: 15 },
    ],
  },
  {
    handle: "sidi-ali",
    sku: "SIDI",
    name: "Sidi Ali",
    category: "Eaux & Soft Drinks",
    description: "Eau minérale naturelle plate",
    image: "sidi-ali.jpg",
    variants: [
      { option1Name: "Format", option1Value: "33cl", price: 6 },
      { option1Name: "Format", option1Value: "50cl", price: 8 },
      { option1Name: "Format", option1Value: "75cl verre", price: 12 },
    ],
  },

  // Jus Frais Pressés
  {
    handle: "jus-orange-presse",
    sku: "JUS-ORA",
    name: "Jus d'Orange Frais Pressé",
    category: "Jus Frais Pressés",
    description: "100% orange fraîches pressées sur place",
    image: "jus-orange.jpg",
    variants: [
      { option1Name: "Taille", option1Value: "Small 25cl", price: 25 },
      { option1Name: "Taille", option1Value: "Medium 40cl", price: 35 },
      { option1Name: "Taille", option1Value: "Large 50cl", price: 45 },
    ],
  },

  // Boissons Ice Lactées
  {
    handle: "ice-latte-vanille",
    sku: "ICE-LAT-VAN",
    name: "Ice Latte Vanille",
    category: "Boissons Ice Lactées",
    description: "Café glacé lait vanille",
    price: 35,
    image: "ice-latte-vanille.jpg",
  },
  {
    handle: "ice-latte-caramel",
    sku: "ICE-LAT-CAR",
    name: "Ice Latte Caramel",
    category: "Boissons Ice Lactées",
    description: "Café glacé lait caramel",
    price: 35,
    image: "ice-latte-caramel.jpg",
  },
  {
    handle: "ice-latte-noisette",
    sku: "ICE-LAT-NOI",
    name: "Ice Latte Noisette",
    category: "Boissons Ice Lactées",
    description: "Café glacé lait noisette",
    price: 35,
    image: "ice-latte-noisette.jpg",
  },
  {
    handle: "ice-mocha",
    sku: "ICE-MOC",
    name: "Ice Mocha",
    category: "Boissons Ice Lactées",
    description: "Café glacé chocolat lait",
    price: 38,
    image: "ice-mocha.jpg",
  },
  {
    handle: "ice-white-mocha",
    sku: "ICE-WHI",
    name: "Ice White Mocha",
    category: "Boissons Ice Lactées",
    description: "Café glacé chocolat blanc lait",
    price: 40,
    image: "ice-white-mocha.jpg",
  },
  {
    handle: "ice-caramel-macchiato",
    sku: "ICE-MAC",
    name: "Ice Caramel Macchiato",
    category: "Boissons Ice Lactées",
    description: "Café glacé caramel macchiato",
    price: 38,
    image: "ice-caramel-macchiato.jpg",
  },
  {
    handle: "ice-matcha-latte",
    sku: "ICE-MAT",
    name: "Ice Matcha Latte",
    category: "Boissons Ice Lactées",
    description: "Matcha glacé lait",
    price: 40,
    image: "ice-matcha-latte.jpg",
  },
  {
    handle: "ice-chai-latte",
    sku: "ICE-CHA",
    name: "Ice Chai Latte",
    category: "Boissons Ice Lactées",
    description: "Chai glacé lait épices",
    price: 40,
    image: "ice-chai-latte.jpg",
  },
];

// Fonction utilitaire pour obtenir les produits par catégorie
export const getProductsByCategory = (category: string): Product[] => {
  return menuProducts.filter((product) => product.category === category);
};

// Fonction utilitaire pour obtenir toutes les catégories uniques
export const getAllCategories = (): string[] => {
  return Array.from(new Set(menuProducts.map((product) => product.category)));
};

// Fonction utilitaire pour obtenir les catégories principales
export const getMainCategories = (): string[] => {
  const categories = getAllCategories();
  return Array.from(
    new Set(categories.map((cat) => cat.split(" - ")[0]))
  ).filter((cat) => cat !== "Modificateurs");
};
